use bootcamp;
## section A
 -- 1	Write a query to print out the unique author names in the dataframe.
select distinct authors from books;
-- 2	Write a query to print the Book count corresponding to each unique author in the dataframe.
select authors,count(authors) book_count from books group by authors;
--  3	Write a query to print out the information about the books published between 1996 to 2006
select * from books where original_publication_year between 1996 and 2006;
--  4	Write a query to print out the information about the books published between 1996 to 2006 and the rating more than 3.5
select * from books where original_publication_year between 1996 and 2006 and average_rating >3.5;
--  5	Write a query to print the book is written by Bill Bryson.
select * from books where authors ='Bill Bryson';
 -- 6	Write a query to print the unique Genre names in the dataframe;
 select distinct Genre from books;
 
--  7	Write a query to print the Book count corresponding to each unique Genre in the dataframe.
 select  Genre,count(Genre) from books  group by Genre;

 -- 8	Write a query to print the Book count corresponding to each unique Genre and which is having rating more than 3.7 in the dataframe.
 select  Genre,count(Genre) from books where average_rating >3.7  group by Genre ;
 -- 9	Write a query to print out the detail of the books whose number of copy sold hasn't been increased by 12.5% from 2017 to 2018
select *  from books where ((Sell_count_2018 -Sell_count_2017)*100/Sell_count_2017)<12.5;
-- 10 Write a query to print the book ids written by Bill Bryson.
select Id from books where authors ='Bill Bryson';
 -- 11 Write a query to find out the name cheapest book
select * from books where Price_per_book = (select min(Price_per_book) from books);
-- 12 Write a query to find out the most expensive book
select * from books where Price_per_book = (select max(Price_per_book) from books);

 -- 13	Write a query to Prepare a column namely Revenue_2017,which will indicate the Revenue generated by the book in 2017.
select b.*, Sell_count_2017*Price_per_book Revenue_2017 from books b;
--  14	Write a query to Prepare a column namely Revenue_2018,which will indicate the Revenue generated by the book in 2018.
select b.*, Sell_count_2018*Price_per_book Revenue_2018 from books b;

-- 15	Write a query to print out the name of the books and the corresponding author names whose Revenue hasn't been increased by 12.5% from 2017 to 2018
select booksoriginal_title,authors  from books where ((Sell_count_2018 -Sell_count_2017)*100/Sell_count_2017)<12.5;

-- 16	Write a query to print out the name of the books and the corresponding author names whose work_text_reviews_count was greater than 100 and rating is more than 3.6
select booksoriginal_title name, authors  from books where Work_text_reviews_count>100 and average_rating>3.6;
-- 17	Write a query to print out the Genre of the books for which it has got the 5 least rating
select Genre from books order by average_rating limit 5;
-- 18	Write a query to print out the Genre of the books for which it has got the 5 least Revenue in 2017
select booksoriginal_title name, authors from books order by  Sell_count_2017*Price_per_book limit 5;
-- 19	Write a query to print out the Genre of the books for which it has got the 5 least Revenue in 2018
select booksoriginal_title name, authors from books order by  Sell_count_2018*Price_per_book limit 5;

 -- 20	Write a query to print out the Genre of the books for which it has got the best Revenue Increase from 2017 to 2018
select * from books  order by (Sell_count_2018 - Sell_count_2017)*Price_per_book desc;
 -- 21	Write a query to show the price Fluctuations for the books written by A.A. Milne, Ernest H. Shepard over the years chronologically
select * from books where authors like '%A.A. Milne%' order by  original_publication_year;
-- 22	Write a query to print out the number of books with non available data in language_code
select  count(*) from books where language_code not in ('en-US','eng','en-GB','en-CA');
-- 23	Write a query to find out number of books written by A.G. Riddle in 2013
select * from books where authors ='A.G. Riddle' and original_publication_year =2013;
-- 24	Write a query to find out the name of the latest book available with rating more than 4.2 in the dataset
select booksoriginal_title from books where average_rating>4.2 order by original_publication_year desc limit 1;
-- 25	Write a query to find out the name of the books which were published before 2000 or after 2015 with the best possible rating written in eng
select booksoriginal_title from books where (original_publication_year <2000 or original_publication_year>2015) and language_code ='eng' order by average_rating desc limit 1;
-- 26	Write a query to find out the name of the latest book available with rating more than 4.5 in the dataset
select * from books where average_rating > 4.5 order by original_publication_year;

##Section B
-- 17	Write a query to show the employee detail where Sr. Leads are earning more than Asst. Managers
select * from employee_details where  Designation ='Sr. Lead' and Salary >
any(select  Salary from employee_details where Designation = 'Asst. Manager');


#section D
use hrboot

 1	Using HR Schema, Write a query to fetch the first name ,last name, name of the department and the location of work of all the employees.
select * from employees 
 2	Using HR Schema, Write a query to fetch the first name ,last name of all the employees who are Sales Representative.

 3	Using HR Schema, Write a Query to fetch all the departments and the names of the person managing them.

 4	Using HR Schema, Write a Query to fetch all the departments and the names of the person managing them in America Region.

 5	Using HR Schema, Write a query to fetch the names of the departments that are unstaffed.

 6	Using HR Schema, Write a query to fetch the names of the departments that are unstaffed and are located in Seattle.

 7	Using HR Schema, Write a query to identify the list of names of employees who are not assigned any work and also the list of departments that are unstaffed so that the employees can be utilised to staff the departments.
	
 8	Using HR Schema, Write a query to identify the list of names of employees who are not assigned any work and also the list of departments that are unstaffed so that the employees can be utilised to staff the departments in London.
	
 9	Using HR Schema, Write a query to list the names of all people who report to the same person.
 
 10	Using HR Schema, Write a query to list the names of all people who report to the same person in department Accounting (i.e.110).

 11	Write a query in SQL to display the first name, last name, department number, and department name for each employee.

 12	Write a query in SQL to display the first and last name, department, city, and state province for each employee.

 13	Write a query in SQL to display the first name, last name, salary, and job grade for all employees.

 14	Write a query in SQL to display the first name, last name, department number and department name, for all employees for departments 80 or 40.

 15	Write a query in SQL to display those employees who contain a letter z to their first name and also display their last name, department, city, and state province.

 16	Write a query in SQL to display all departments including those where does not have any employee.

 17	Write a query in SQL to display the first name of all employees including the first name of their manager.

 18	Write a query in SQL to display the department name, city, and state province for each department.

 19	Write a query in SQL to display the first name of all employees and the first name of their manager including those who does not working under any manager.

 20	Write a query in SQL to display the first name, last name, and department number for those employees who works in the same department as the employee who holds the last name as Taylor

 21	Write a query in SQL to display the job title, department name, full name (first and last name ) of employee, and starting date for all the jobs which started on or after 1st January, 1993 and ending with on or before 31 August, 1997.

 22	Write a query in SQL to display the name of the department, average salary and number of employees working in that department who got commission.

 23	Write a query in SQL to display the country name, city, and number of those departments where at least 2 employees are working.

 24	Write a query in SQL to display the department name and number of employees in each of the department.

-- 25	Write a query in SQL to display the full name (first and last name ) of employee with ID and name of the country presently where (s)he is working

Write a Query to display the word 'Great Learning' by removing the  vowels.
select  replace('Great Learning',('a','e'),'')


select ('01-01-2020') from dual